[#5] 로그인 및 로그아웃 기능 구현
f-lab-edu/go-table pull request #12
Opened 2024-05-23 13:08 UTC by syoh98

## 📌 Issue
#5     
## 📝 작업 사항
* 세션에 회원 id를 저장 및 제거하여 로그인 및 로그아웃 기능을 구현했습니다.
* Session Storage 구현체로 Redis를 적용했습니다.
* 로그인한 상태 즉, 인증 상태를 확인할 수 있는 인터셉터를 적용했습니다.

2024-05-24 12:57 UTC, f-lab-maverick requested changes
- 로그인 구현에 `Spring Security`를 사용하지 않은 이유를 관련 코드에 주석으로 명시해주세요.
- FIlter / Interceptor 중 Interceptor를 선택하고 구현한 이유를 주석으로 작성해주세요.

위 두가지는 소스코드를 읽는 많은 사람들이 궁금해할만한 이슈입니다.
 나머지는 리뷰 확인 후 재요청주세요~

2024-05-24 12:57 UTC, f-lab-maverick commented on src/main/java/flab/gotable/Interceptor/LoginInterceptor.java
> +        if(request.getSession().getAttribute(MEMBER_ID) == null) {
로그인된 유저인지를 판단하거나 / 유저 정보를 가져오는 `request.getSession().getAttribute(MEMBER_ID)` 메서드는 꽤나 반복적으로 사용될 것으로 보입니다.  이렇게 공통적으로 사용되는 로직은 `Util` 또는 별도 메서드로 분리해주시는게 좋습니다.

ex) `if (hasAuthentication(request)) { ...`
ex) `if (SecurityUtils.isLogin()) { ...`

2024-05-24 12:57 UTC, f-lab-maverick commented on src/main/java/flab/gotable/config/RedisConfig.java
> +        redisTemplate.setValueSerializer(new GenericJackson2JsonRedisSerializer());
동일한 Object를 `StringRedisSerializer`로 직렬화할 때랑 `GenericJackson2JsonRedisSerializer`로 직렬화할 때는 어떤 차이가 있을까요?

2024-05-24 12:57 UTC, f-lab-maverick commented on src/main/java/flab/gotable/config/WebConfig.java
> +                .excludePathPatterns("/members/signup", "/members/login");
이렇게 특정 패턴만 인터셉터에서 제외하고 보안조치를 무시하는 방식을 화이트리스트 방식이라고 합니다.
이 방식을 선택한 이유가 있을까요? 다른방식은 어떤 방식이 있을까요?

2024-05-24 12:57 UTC, f-lab-maverick commented on src/main/java/flab/gotable/controller/MemberAPIController.java
> +        if(!memberService.findMemberByIdAndPassword(memberLoginRequestDto)) {
`memberService.findMemberByIdAndPassword`는 메서드 네이밍으로 본다면 회원 데이터를 조회하는 역할일 것으로 기대됩니다. 하지만 해당 메서드는 boolean값을 리턴하고 있네요. 이 경우 메서드를 사용하는 다른 개발자가 혼동하거나 소스코드 가독성을 하락시키는 요인이 됩니다.

boolean 값을 리턴하는 경우 메서드의 이름은 `is~~`, `can~~` 등 명확하게 true/false를 나타내는 네이밍이어야 합니다.

2024-05-24 12:57 UTC, f-lab-maverick commented on src/main/java/flab/gotable/exception/ExceptionController.java
> +    }
MemberNotFoundException, UnAuthenticatedException 모두 동일한 로직을 따르고있네요. 동일한 로직인데 핸들러를 두 개 만들 필요가 있나요?

2024-05-24 12:57 UTC, f-lab-maverick commented on src/main/java/flab/gotable/service/MemberService.java
> +        }
이런 경우 간단하게 아래 표현으로 간결하게 작성할 수 있습니다.
```suggestion
        return passwordEncoder.matches(memberLoginRequestDto.getPassword(), member.getPassword())
```

2024-05-24 12:57 UTC, f-lab-maverick commented on src/test/java/flab/gotable/controller/MemberAPIControllerTest.java
> +                        }
초기화 코드가 상당히 길어지고 있네요~ 이를 줄일 좋은 방법은 없을까요?

2024-05-24 12:57 UTC, f-lab-maverick commented on src/test/java/flab/gotable/controller/MemberAPIControllerTest.java
> +    @DisplayName("로그인에 성공할 경우 200 OK를 반환한다.")
적절한 테스트케이스 👍

2024-05-24 12:57 UTC, f-lab-maverick commented on src/test/java/flab/gotable/controller/MemberAPIControllerTest.java
> +    @DisplayName("가입한 회원 정보를 찾지 못해 로그인에 실패할 경우 MemberNotFoundException 예외를 발생시킨다.")
패스워드가 틀릴 경우도 테스트해주세요~ (동일한 실패조건이라도 비즈니스로직적으로 다른 로직이기에 테스트해야 합니다.)

2024-05-24 12:57 UTC, f-lab-maverick commented on src/main/java/flab/gotable/service/LoginService.java
> +}
LoginService 내부에 HttpSession을 상태로 왜 가지게 해두신건가요?
이렇게 하면 NPE가 발생할 것이고, 로그인또한 되지 않을 것입니다.

2024-05-24 12:57 UTC, f-lab-maverick commented on src/test/java/flab/gotable/service/LoginServiceTest.java
LoginService의 설계가 잘못되어 테스트코드도 복잡해졌네요. 해당 서비스로직을 상태를 가지지 않도록 수정해보세요~

2024-05-30 22:22 UTC, syoh98 commented
> 로그인 구현에 `Spring Security`를 사용하지 않은 이유를 관련 코드에 주석으로 명시해주세요.
  * 로그인/로그아웃을 구현하며 `인증` 기능을 구현하는데 집중했고, 해당 기능은 Spring Security 없이 구현이 가능하다고 판단했습니다. 다른 보안적인 요소를 추가하게 된다면 추후 Spring Security를 도입해도 될 것 같다고 생각하여 Spring Security를 사용하지 않았습니다.
> FIlter / Interceptor 중 Interceptor를 선택하고 구현한 이유를 주석으로 작성해주세요.
  * `Filter`는 스프링 범위 밖에서 모든 서블릿 요청을 받아 처리하기 때문에 스프링에 의해 필터링되는 요청들을 전부 받습니다. 반면 `Interceptor`는 스프링 영역에서 동작하기 때문에 성능적인 면에서 이점이 있을거라 판단했습니다. 또한 Interceptor는 Spring이 제공하는 기술로 예외 발생 시 따로 예외 처리를 해야하는 필터와 다르게  `@ControllerAdvice`로 공통적인 예외처리가 가능한 것과 같이 스프링 컨테이너와의 통합성이 높은 것이 장점이라 생각하여 Interceptor로 구현했습니다.

결론적으로 `인증` 기능에 집중하여 구현하다보니 개발하기 편한 쪽을 선택하여 보안적인 측면을 고려하지 못한 것 같습니다.
`XSS`, `CSRF` 등 공격에 대한 보안을 강화하고 싶고, 이를 개발하기에 편리한 `Spring Security` 도입으로 인증을 다시 구현하고자 합니다!

2024-05-30 22:25 UTC, syoh98 commented on src/main/java/flab/gotable/config/WebConfig.java
> +                .excludePathPatterns("/members/signup", "/members/login");
다른 방식으로는 `블랙리스트`가 있습니다. 블랙리스트 방식은 허용되지 않은 항목들만 명시적으로 차단하고, 나머지는 모두 접근을 허용하는 방식입니다.
화이트리스트 방식은 모든 항목 차단을 바탕으로 허용된 항목들만 접근할 수 있기 때문에 보안적으로 더 안전할 것이라 판단했는데, 제가 놓친 부분이 있을까요?

2024-05-30 22:26 UTC, syoh98 commented on src/test/java/flab/gotable/controller/MemberAPIControllerTest.java
> +                        }
LoginService에서 HttpSession을 상태로 가지지 않도록 수정하겠습니다.

2024-05-30 22:37 UTC, syoh98 commented on src/main/java/flab/gotable/service/LoginService.java
> +}
HttpSession을 상태로 가지면 모든 요청이 하나의 HttpSession을 통해 들어오는데, 이 점을 고려하지 못했습니다. 이 부분 수정하겠습니다!

2024-06-12 12:46 UTC, syoh98 commented on src/main/java/flab/gotable/config/RedisConfig.java
> +        redisTemplate.setValueSerializer(new GenericJackson2JsonRedisSerializer());
* `StringRedisSerializer`: 객체를 **문자열**로 직렬화합니다.
* `GenericJackson2JsonRedisSerializer`: Jackson 라이브러리를 사용하여 객체를 **JSON 형식**으로 직렬화합니다. 
   

`GenericJackson2JsonRedisSerializer`는 별도의 Class Type을 지정하지 않아도 자동으로 직렬화를 해주는 반면  `StringRedisSerializer`는 객체를 특정 형태(ex.JSON)로 저장하기 위해서는 직접 직렬화하는 로직을 구성해줘야 하는 차이가 있습니다.

2024-06-12 13:29 UTC, f-lab-maverick commented on src/main/java/flab/gotable/service/LoginService.java
> +}
Spring MVC구현을 보면 `private final HttpSession httpSession`을 bean으로 가지는 경우 요청마다 알아서 Session을 할당해주네요. 이 방식으로도 구현이 가능하나, 테스트의 편의성과 소스코드 로직의 가독성을 위해서는 수정해주시는게 좋겠습니다.

2024-06-12 13:39 UTC, f-lab-maverick requested changes
테스트 케이스가 늘어났고 꽤 좋은 코드가 점점 보이는군요 👍 👍 
하지만 아직 승인을 받으려면 몇가지 수정사항이 더 수정되어야 합니다.
간단한 수정사항이므로 수정 후 다시 요청주세요~

2024-06-12 13:39 UTC, f-lab-maverick commented on src/main/java/flab/gotable/Interceptor/LoginInterceptor.java
> +* */
👍

2024-06-12 13:39 UTC, f-lab-maverick commented on src/main/java/flab/gotable/controller/MemberAPIController.java
> +        if(!memberService.isvalidMember(memberLoginRequestDto)) {
`isvalidMember` -> `isValidMember`

2024-06-12 13:39 UTC, f-lab-maverick commented on src/main/java/flab/gotable/exception/ExceptionController.java
> +                .body(ApiResponse.fail(new ObjectMapper().writeValueAsString(map)));
매 핸들링마다 마다 `new ObjectMapper`를 하여 객체를 생성하는것도 비용이니 불필요한 객체 생성 비용을 줄이기 위해 `ExceptionController` 의 상태로 미리 ObjectMapper를 생성해두고, 이를 재사용하는 방안을 사용해 보시는건 어떠신가요?

2024-06-12 13:39 UTC, f-lab-maverick commented on src/main/java/flab/gotable/utils/SecurityUtils.java
> +    }
메서드 이름이 `hasAuthentication`으로, 인증된 사용자인지 아닌지 true/false를 리턴하는 메서드 명이지만 실제로 리턴하는 것은 회원의 아이디입니다.

해당 메서드의 기능이 인증된 사용자인지 여부를 판단하는 기능이라면 리턴타입을 `boolean`으로 변경해주시고,
추가적으로 현재 유저의 아이디를 세션에서 조회하는 기능이 필요하다면 별도 메서드로 만들어주세요~

2024-06-12 13:39 UTC, f-lab-maverick commented on src/test/java/flab/gotable/service/LoginServiceTest.java
이 테스트는 서비스 레이어의 테스트가 아닌, API레벨 테스트입니다.
해당 테스트클래스의 이름을 API 테스트에 맞게 변경해주세요.
`LoginAPITest` 등 여러 이름이 나올 수 있겠네요.

2024-06-12 14:16 UTC, syoh98 commented on src/main/java/flab/gotable/utils/SecurityUtils.java
> +    }
인증된 사용자인지 여부를 판단의 기능을 하는 메서드로 `boolean` 타입으로 변경하겠습니다.

2024-06-12 21:38 UTC, f-lab-maverick approved these changes
고생하셨습니다! 머지해주셔도 좋습니다.

2024-06-12 22:48 UTC, merged