[#13] 식당 상세 조회 기능 구현
f-lab-edu/go-table pull request #14
Opened 2024-07-10 17:53 UTC by syoh98

## 📌 Issue
#13 
## 📝 작업 사항
* 식당 상세 조회 기능을 구현했습니다. 
* POJO 방식으로 식당 상세 조회 기능에 대한 단위 테스트를 진행했습니다.

2024-07-11 13:17 UTC, f-lab-maverick requested changes
고생하셨습니다. 이번 PR에서는 전체적인 코드 작성 스타일에 대한 습관을 교정하는 작업을 진행해야 할 것으로 보입니다. 수정 후 다시 리뷰요청 주세요~

2024-07-12 13:37 UTC, syoh98 commented on src/main/java/flab/gotable/controller/StoreAPIController.java
> +                .body(ApiResponse.ok(storeDetails, "식당 상세 조회 성공"));
API Reponse로 Map 사용을 지양하는 이유에 대해 더 찾아본 결과, 
* 타입 캐스팅 비용 발생
* 컴파일 에러 미발생
* 가독성 저하

등의 이유로 Map 대신 DTO를 사용하는 것을 알게되었습니다. 이 점 유의해서 코드 작성하겠습니다.

2024-07-12 13:40 UTC, syoh98 commented on src/main/java/flab/gotable/domain/entity/DailySchedule.java
> +    private String closeTime;
DailySchedule, SpecificSchedule의 openTime, closeTime 타입 모두 시간만을 표현하는 데이터로 명확한 형식 표현을 위해`LocalTime`으로 수정하겠습니다!

2024-07-12 13:49 UTC, syoh98 commented on src/main/java/flab/gotable/service/StoreService.java
> +        int interval = Integer.parseInt(splitTime);
현재 `splitTime`은 1시간 단위라면 "60"을, 30분 단위라면 "30"을 DB에 저장하고 있습니다.

2024-07-12 13:51 UTC, syoh98 commented on src/main/java/flab/gotable/service/StoreService.java
> +            dayInfo.put("selectableTimes", selectableTimes);
시도는 해보겠습니다!

2024-07-12 14:01 UTC, syoh98 commented on src/main/java/flab/gotable/service/StoreService.java
> +        Map<String, Object> availableDays = new LinkedHashMap<>();
availableDays의 예약 가능한 날짜를 순서대로 조회하기 위함이었습니다.

2024-07-13 00:00 UTC, f-lab-maverick commented on src/main/java/flab/gotable/service/StoreService.java
> +        Map<String, Object> availableDays = new LinkedHashMap<>();
이후에는 순서나 인덱스가 필요하다면 Map이 아닌 List타입을 사용해주세요~
Map 내부에 아무리 정렬을한들 Map타입이 직렬화되면 javascript에서는 object타입으로 변경되기때문에 어차피 클라이언트 내부적으로 정렬처리를 해주게됩니다.

2024-07-13 00:33 UTC, f-lab-maverick requested changes
약간만 더 수정하면 될거같습니다! 파이팅입니다.
확인 후 다시 리뷰요청해주세요.

2024-07-13 00:33 UTC, f-lab-maverick commented on src/main/java/flab/gotable/domain/entity/DailySchedule.java
> +    private String day;
아직 String 타입이 남아있네요~
작성하신 클래스들을 확인하여서 날짜타입과 시간타입은 String이 아닌 명시적인 타입을 쓰도록 변경해주세요.

2024-07-13 00:33 UTC, f-lab-maverick commented on src/main/java/flab/gotable/service/StoreService.java
> +        }
if-else 내부에 또 if-else가 있는 등, if 문 내부에 if문이 들어가는 행위는 지양해주세요.
이게 중첩되면 이 코드가 실행되는 조건을 파악하기가 정말 어려워지거든요.

이걸 해결하는 패턴은 [early return pattern](https://medium.com/swlh/return-early-pattern-3d18a41bba8) 입니다. else문을 안쓰고 if문내부에서 return 처리하는 방식이니 키워드로 찾아보시고 적용해보세요.

2024-07-13 00:33 UTC, f-lab-maverick commented on src/main/java/flab/gotable/service/StoreService.java
> +    }
null 가능성이 있는 메서드/상태에 `@Nullable` 어노테이션을 붙여두면 코드편집기에서 해당 메서드가 null 가능성이 있다는 경고를 띄워주며, null처리를 하도록 도와줍니다.
NPE 방지를 위해 null을 리턴할 수 있는 메서드에는 위 어노테이션을 붙여주세요.
```suggestion
    @Nullable
    private SpecificSchedule findSpecificSchedule(LocalDate targetDate, List<SpecificSchedule> specificSchedules) {
        return specificSchedules.stream()
                .filter(s -> s.getDate().equals(targetDate))
                .findFirst()
                .orElse(null);
    }
```

2024-07-13 00:33 UTC, f-lab-maverick commented on src/main/java/flab/gotable/service/StoreService.java
> +        int interval = Integer.parseInt(splitTime);
그렇다면 interval은 int 타입이 아닌 `Duration` 타입을 사용해보세요.
해당 타입은 시간을 다룰 때 기간을 저장하며, 저장한 기간을 시/분/초 등의 단위로 변환하기에도 편리합니다.
이 프로젝트는 '시간' / '기간' 등을 많이 다루는만큼 아래 내용을 참고해 적용해보세요~
https://www.baeldung.com/java-period-duration

2024-07-13 07:32 UTC, syoh98 commented on src/main/java/flab/gotable/domain/entity/DailySchedule.java
> +    private String day;
요일(Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday)을 나타내는 열거형인 `DayOfWeek`을 사용하여 명시적인 타입을 사용하도록 하겠습니다!

2024-07-13 07:44 UTC, syoh98 commented on src/main/java/flab/gotable/service/StoreService.java
> +        int interval = Integer.parseInt(splitTime);
해당 내용을 참고하여 Duration을 적용해 봤을 때, String 타입인 splitTime이 `PnDTnHnMn.nS` 형식을 갖추어야 함을 알게 되었습니다. 문자열 파싱 과정이 불필요하다 생각되어 splitTime의 타입을 String에서 Long으로 변경했습니다!

2024-07-13 10:32 UTC, f-lab-maverick approved these changes
고생하셨습니다. 머지해주셔도 좋습니다~ 다음 이슈 개발 진행하시죠!

2024-07-13 12:02 UTC, merged