[#7] 예약 기능 구현
f-lab-edu/go-table pull request #15
Opened 2024-08-01 18:04 UTC by syoh98

## 📌 Issue
#7 
## 📝 작업 사항
* 예약 기능을 구현했습니다. 
* 동시성 제어를 위해 비관적 락(Pessimistic lock)을 사용했습니다.

2024-08-02 13:42 UTC, f-lab-maverick requested changes

2024-08-02 13:42 UTC, f-lab-maverick commented on src/main/java/flab/gotable/dto/response/ReservationResponseDto.java
> +    private Long memberCount;
`@RequiredArgsConstructor`가 동작하지 않고 기본 생성자를 생성할것으로 보이네요. 의도하신바가 맞으실까요?

2024-08-02 13:42 UTC, f-lab-maverick commented on src/main/java/flab/gotable/dto/response/ReservationResponseDto.java
> +    private Long memberCount;
Wrapper Type에 대한 사용이 지속적으로 보입니다. `memberCount`가 null인 상황이 필요하지 않다면 primitive type을 사용해주세요.

2024-08-02 13:42 UTC, f-lab-maverick commented on src/main/java/flab/gotable/service/ReservationService.java
> +            if (!isReservationAvailable(restaurantId, reservationStartTime, reservationEndTime)) {
ealry throw 패턴을 사용하면 락 획득에 실패한 경우를 좀 더 깔끔하게 처리할 수 있습니다.

```suggestion
        // 락 획득 여부
        if(reservationMapper.getRestaurantLock(reservationRequestDto.getRestaurantId()) <= 0) {
          // 락 획득에 실패
          throw new ...
        }
        
        // 예약하려는 시간이 일반 또는 영업 스케줄 중에 존재하는지
            if (!isExistSchedule(restaurantId, reservationStartTime, reservationEndTime)) {
                throw new ScheduleNotFoundException(ErrorCode.RESERVATION_TIME_NOT_FOUND, ErrorCode.RESERVATION_TIME_NOT_FOUND.getMessage());
            }
            ...
```

2024-08-02 13:42 UTC, f-lab-maverick commented on src/main/resources/mapper/ReservationMapper.xml
> +        AND close_time &gt;= #{endTime}
`startTime < targetTime < closeTime` 이 아닌, `startTime <= targetTime <= closeTime` 형식으로 비교해야하지 않을까요?
between 문을 쓰시면 더 깔끔해질것 같습니다.

2024-08-02 13:42 UTC, f-lab-maverick commented on src/main/resources/mapper/ReservationMapper.xml
> +        AND close_time &gt;= #{endTime}
이 부분도 마찬가지입니다.

2024-08-02 13:42 UTC, f-lab-maverick commented on src/main/resources/mapper/ReservationMapper.xml
> +        AND close_time &gt;= #{endTime}
그리고 위 쿼리로 했을 때 아리 케이스중 잡아내지 못하는 케이스는 어떤 케이스일까요? 
예약이라는 것은 시작과 종료시간이 무조건 일치하는것만 찾으시면 안됩니다.

(오소영이 예약을 시도하려할 때 발생가능한 케이스 일부)
![image](https://github.com/user-attachments/assets/43c0fd2a-e328-4249-ac49-262d7c1e2a09)

2024-08-02 13:42 UTC, f-lab-maverick commented on src/main/resources/mapper/ReservationMapper.xml
> +    </select>
이것도 중복예약을 모두 필터링하지 못하겠네요.

2024-08-02 13:42 UTC, f-lab-maverick commented on src/main/resources/mapper/ReservationMapper.xml
> +    </select>
Select문에서 비관적락을 명시적으로 획득하지 않는다면 이 쿼리는 락 없이도 실행 가능하지 않을까요?

2024-08-02 13:42 UTC, f-lab-maverick commented on src/main/java/flab/gotable/service/ReservationService.java
> +        final String dayOfWeek = reservationStartTime.getDayOfWeek().toString();
sql.Date / sql.Time을 사용하시는 이유가 있나요?
하나의 어플리케이션에서 활용하는 시간타입은 하나로 통일해야 합니다. 명시적인 이유가 있다면 해당 타입으로 모두 통일해주시고, 그게 아니라면 `LocalDateTime` / `LocalDate` / `LocalTime` 등 java.time 패키지 내부에 있는 시간타입을 사용해주세요.

통일되지않은 타입이 혼용된다면 위와같이 계속해서 타입변환이 필요합니다.

2024-08-04 09:31 UTC, syoh98 commented on src/main/java/flab/gotable/domain/entity/Reservation.java
> +    private Long seq;
id는 예약 번호, seq는 회원 seq와 매칭됩니다. 혼동을 일으키는 것 같네요. seq를 memberSeq로 변경하겠습니다!

2024-08-04 09:35 UTC, syoh98 commented on src/main/java/flab/gotable/domain/entity/Reservation.java
> +    private Timestamp reservationEndAt;
DB에 선언한 타입인 timestamp를 그대로 가져오려고 Timestamp 타입을 사용한 것인데, 타입 선언에 대한 고민이 부족했던 것 같습니다.
* `Timestamp`타입은 가변 객체로 상태를 변경할 수 있는 반면 `LocalDateTime` 타입은 불변 객체로 한 번 생성되면 상태를 변경할 수 없기 때문에 스레드로부터 안전합니다.
* 또한 `Timestamp`타입은 시스템의 timezone 설정에 영향을 받고, `LocalDateTime`은 timezone 정보를 포함하지 않는 특징을 갖고 있습니다.   

따라서, `Timestamp`타입보다 **타입 안정성을 보장**하고 **일관된 날짜와 시간을 표현**할 수 있는 `LocalDateTime`타입을 사용합니다.

https://docs.oracle.com/javase/8/docs/api/java/time/LocalDateTime.html
https://docs.oracle.com/javase/8/docs/api/java/util/Date.html
https://docs.oracle.com/javase/8/docs/api/java/sql/Timestamp.html

2024-08-04 09:35 UTC, syoh98 commented on src/main/java/flab/gotable/dto/request/ReservationRequestDto.java
> +    private LocalDateTime reservationEndTime;
그러네요.. LocalDateTime 타입으로 통일시키겠습니다.

2024-08-04 09:35 UTC, syoh98 commented on src/main/java/flab/gotable/dto/response/ReservationResponseDto.java
> +    private Long memberCount;
습관적으로 사용했습니다.. `@RequiredArgsConstructor` 어노테이션 제거 하겠습니다.
이 점 앞으로 코드 작성할 때 유의하겠습니다~!

2024-08-04 22:50 UTC, syoh98 commented on src/main/resources/mapper/ReservationMapper.xml
> +        AND close_time &gt;= #{endTime}
![354933626-9f2dedbb-d928-48e1-91cd-13b180632ff2](https://github.com/user-attachments/assets/c3e7ef91-7c65-4a40-b28d-7617d290abf7)
현재 쿼리로 각 테스트 케이스를 실행해보았을 때, 결과에 이상이 없어 그대로 두겠습니다~!

2024-08-05 09:29 UTC, f-lab-maverick approved these changes
고생하셨습니다. 머지해주셔도 좋습니다. 다음은 named lock을 활용한 비즈니스로직 락을 구현해보시죠.

2024-08-05 09:29 UTC, f-lab-maverick commented on src/main/java/flab/gotable/dto/StatusCode.java
> +    private final String value;
value가 꼭 필요할지도 고려가 필요하겠네요.
ENUM의 name 속성을 사용하면 별도로 value가 필요없을 것으로 보이는데, value를 사용할만한 상황이 있을까요?

2024-08-05 09:29 UTC, f-lab-maverick commented on src/main/java/flab/gotable/dto/response/ReservationResponseDto.java
> +    }
생성자를 잘 활용하고 계시네요 👍

2024-08-05 09:29 UTC, f-lab-maverick commented on src/main/resources/mapper/ReservationMapper.xml
> +        AND close_time &gt;= #{endTime}
이 테스트케이스를 테스트코드로도 작성해두면 좋겠네요~

2024-08-05 10:05 UTC, syoh98 commented on src/main/java/flab/gotable/dto/StatusCode.java
> +    private final String value;
사용할만한 상황은 아직 없는 것 같습니다. 다음 PR 때 수정해서 올리도록 하겠습니다.

2024-08-05 10:06 UTC, merged