[#4] 회원가입 기능 구현
f-lab-edu/go-table pull request #9
Opened 2024-03-27 18:43 UTC by syoh98

## 📌 Issue
#4    
## 📝 작업 사항
* MyBatis를 연동했습니다.
* Controller, Service, Repository와 Request, Response DTO를 생성했습니다.
* 회원가입 기능을 구현했습니다.
* 비밀번호 암호화 방식은 다음과 같은 이유로 ``` bcrypt ```를 선택했습니다
  *  MD5, SHA256는 레인보우 테이블 이슈를 방지하기 위해 따로 salt 값을 추가하여 암호화해야 하지만, bcrypt는 무작위 salt 값을 생성해주어 따로 값을 추가하지 않아도 됩니다.
  * bcrypt는 무작위 salt와 함께 원본 비밀번호가 여러번 해싱이 가능합니다. 때문에 무차별 대입 공격을 수행하기 어렵습니다.

2024-03-28 10:48 UTC, f-lab-maverick requested changes
첫 PR 고생하셨습니다~ 리뷰 확인 후 수정해주세요~

2024-03-28 10:48 UTC, f-lab-maverick commented on src/main/java/flab/gotable/GoTableApplication.java
> +@SpringBootApplication(exclude = {SecurityAutoConfiguration.class})
`SecurityAutoConfiguration`은 왜 제외한 설정을 진행하셨나요?

2024-03-28 10:48 UTC, f-lab-maverick commented on src/main/java/flab/gotable/controller/MemberAPIController.java
> +    }
status를 포함한 값을 내려줄 수 있는 `ResponseEntity`를 반환값으로 이미 사용중인데요, `@ResponseStatus(HttpStatus.OK)`는 불필요하지 않을까요?

2024-03-28 10:48 UTC, f-lab-maverick commented on src/main/java/flab/gotable/controller/MemberAPIController.java
> +        ResponseDto res = new ResponseDto(HttpStatus.OK, "SUCCESS");
1. `"SUCCESS"`라는 값이 같이 반환되어야할 이유가 있을까요? 200번대 HTTP Response status로 성공 여부를 이미 표현할 수 있으므로 불필요하지 않을까요? 이렇게 성공이라는 status값과 성공이라는 문자열이 함께 내려갈 경우 클라이언트측에서 혼동이 올 수 있습니다. 만약 200 status + "FAIL"이라는 값이 반환된다면 해당 요청이 성공한 것일까요 실패한 것일까요? 이를 클라이언트가 판단할 수 있을까요?
2. 성공을 나타내는 HTTP Status값은 200 이외에도 여러가지가 있습니다. 200은 가장 쓰기 좋은 반면, 어떤 성공을 했는지 나타내기 어려운 반환값이기도 합니다. "리소스의 생성이 완료되었다"를 나타내는 status는 어떤 값이 있을까요?

2024-03-28 10:48 UTC, f-lab-maverick commented on src/main/java/flab/gotable/controller/MemberController.java
> +}
현재 완성되지 않은 부분으로 보이네요~ 이런 코드는 push하지 않는게 좋습니다. 미완성 코드가 운영상에 포함될 수 있으니까요~

2024-03-28 10:48 UTC, f-lab-maverick commented on src/main/java/flab/gotable/dto/response/MemberSignUpResponseDto.java
> +}
회원데이터의 반환값에 `password`가 포함되어있네요. 비밀번호를 꼭 반환할 필요가 있나요?

2024-03-28 10:48 UTC, f-lab-maverick commented on src/main/java/flab/gotable/repository/MemberRepository.java
> +public interface MemberRepository {
이 클래스는 `Repository`가 아닌 `Mapper`의 역할을 하고 있기 때문에 `MemberMapper`라는 네이밍이 더 적절해보입니다~ Mapper / Repository의 차이는 어떤 것일까요? 한번 찾아보시고 답글로 달아보시겠어요?

2024-03-28 10:48 UTC, f-lab-maverick commented on src/main/java/flab/gotable/service/MemberService.java
> +    }
1. 회원가입 로직에 트랜잭션이 걸려있지 않네요. 트랜잭션을 적용하지 않은 이유가 있나요?
2. `BCryptPasswordEncoder `를 회원가입 요청이 올 때 마다 객체를 생성해야할 이유가 있나요? 매번 객체를 생성하면 불필요한 메모리 점유와 성능 저하가 생기지 않을까요?

2024-03-28 10:48 UTC, f-lab-maverick commented on src/main/java/flab/gotable/service/MemberService.java
> +    }
회원가입로직이라면 이 메서드 내부에서 `Member`를 생성해서 저장해야하는데 Service레이어에서 Member 인스턴스를 상수로 만들어서 사용하고 있네요. 의도하신 로직이 맞을까요? 이런 형식으로 만들면 어떤 이슈가 발생할까요?

2024-03-28 10:48 UTC, f-lab-maverick commented on src/main/java/flab/gotable/service/MemberService.java
> +    final Member member = new Member();
상수로 만들어진 `member`가 서비스 레이어에서 비즈니스로직에 참여하고 있습니다. 여러 스레드가 이 인스턴스를 사용할텐데 문제가 없을까요?

2024-03-28 10:48 UTC, f-lab-maverick commented on src/main/resources/mapper/MemberMapper.xml
> +        VALUES(NULL, #{name}, #{id}, #{password}, #{phone})
seq를 null로 입력할 수 있나요? seq가 일반적으로는 pk로 입력될텐데요, seq를 auth_increment값으로 입력하려는 의도라면 아예 쿼리에서 seq를 빼주시는게 명시적입니다.

```suggestion
        (NAME, ID, PASSWORD, PHONE)
        VALUES(#{name}, #{id}, #{password}, #{phone})
```

2024-03-28 10:48 UTC, f-lab-maverick commented on src/main/resources/mapper/MemberMapper.xml
> +        VALUES(NULL, #{name}, #{id}, #{password}, #{phone})
MyBatis의 최초 리뷰이니 추가적인 질문을 하나 드리자면, `#{}` / `${}`형식의 변수 매핑은 어떤 차이가 있을까요?

2024-03-28 10:48 UTC, f-lab-maverick commented on src/main/resources/templates/signup.html
> +</html>
테스트를 위해 회원가입 페이지를 만드신거같네요~ 우선 회원가입페이지 없이 API로만 프로젝트를 만들어주시고, 실제 테스트는 Postman등의 툴을 이용해주세요.

2024-03-29 12:07 UTC, syoh98 commented on src/main/resources/mapper/MemberMapper.xml
> +        VALUES(NULL, #{name}, #{id}, #{password}, #{phone})
* ``` #{} ```: PreparedStatement 생성 후 parameter를 바인딩합니다. parameter를 하나의 값(value)로 인식하기 때문에 문자열에 따옴표가 붙습니다.
* ``` ${} ```: Statement 생성 후 parameter 값을 그대로 전달합니다. 때문에 문자열에 따옴표가 붙지 않습니다.
   
따라서 ``` #{} ```은 parameter가 String 형태로 들어오고,  ``` ${} ```은 parameter가 해당 컬럼의 자료형 형태 그대로 들어온다는 차이가 있습니다.

2024-03-29 12:31 UTC, syoh98 commented on src/main/java/flab/gotable/GoTableApplication.java
> +@SpringBootApplication(exclude = {SecurityAutoConfiguration.class})
spring security 의존성을 주입하면 자동으로 추가되는 기본 로그인 페이지를 제거하고자 옵션을 주었습니다.
다시 찾아보니, 해당 옵션 사용 시 spring security 가 제공하는 기능 일부 또는 전부를 사용할 수 없기 때문에 해당 설정 제거하겠습니다.

2024-03-29 13:04 UTC, syoh98 commented on src/main/java/flab/gotable/controller/MemberAPIController.java
> +    }
맞습니다. status code를 중복해서 받을 필요 없기 때문에 ``` @ResponseStatus(HttpStatus.OK) ``` 제거하도록 하겠습니다.

2024-03-30 03:24 UTC, syoh98 commented on src/main/java/flab/gotable/repository/MemberRepository.java
> +public interface MemberRepository {
``` MemberMapper ```로 클래스 이름 수정하겠습니다!

* ``` Mapper ```: 객체와 DB간의 매핑을 처리하는 역할을 합니다. SQL 쿼리를 직접 작성해야합니다.
* ``` Repository ```: DB의 데이터 조회 및 조작하는 역할을 합니다. 인터페이스를 제공하기 때문에 SQL 쿼리를 직접 작성하지 않아도 됩니다.

2024-03-30 04:01 UTC, syoh98 commented on src/main/java/flab/gotable/dto/response/MemberSignUpResponseDto.java
> +}
반환할 필요 없습니다. ``` password ``` 제거하겠습니다!

2024-03-31 05:19 UTC, syoh98 commented on src/main/java/flab/gotable/controller/MemberAPIController.java
> +        ResponseDto res = new ResponseDto(HttpStatus.OK, "SUCCESS");
1. 동일하게 "성공"의 의미인 HTTP Status와 Message를 같이 사용하여 클라이언트 혼란을 유발한 것 같습니다.  이 부분 수정하겠습니다! 
2. HTTP status를 찾아본 결과, 클라이언트의 요청이 성공적으로 이뤄졌다는 의미에 더하여 새로운 리소스가 생성되었다는 HTTP Status는 ``` 201 Created ``` 입니다.
[https://developer.mozilla.org/ko/docs/Web/HTTP/Status](url)

2024-03-31 06:50 UTC, syoh98 commented on src/main/java/flab/gotable/service/MemberService.java
> +    }
1. 회원가입 로직에 비밀번호를 암호화하는 로직이 포함되어있어 트랜잭션을 최소화 하고자 ``` saveMember ```에 트랜잭션을 적용했습니다.
2. 맞습니다. 불필요한 메모리 점유와 성능 저하를 방지하기 위해 ``` BCryptPasswordEncoder ``` 를 전역변수로 선언하겠습니다.   
      
   
> 회원가입로직이라면 이 메서드 내부에서 `Member`를 생성해서 저장해야하는데 Service레이어에서 Member 인스턴스를 상수로 만들어서 사용하고 있네요. 의도하신 로직이 맞을까요? 이런 형식으로 만들면 어떤 이슈가 발생할까요?   

상수로 선언하면 해당 인스턴스는 수정할 수 없습니다. `memberSignUpRequestDto`로 받아온 값을 member에 set하더라도 변경이 불가능합니다. 의도한 로직이랑 다릅니다. 이 부분 수정하겠습니다!

2024-03-31 08:33 UTC, syoh98 commented on src/main/java/flab/gotable/service/MemberService.java
> +    final Member member = new Member();
여러 스레드에서 `member`를 참조해서 값을 변경하면 동시성 이슈가 발생합니다. 수정하겠습니다.

2024-03-31 13:04 UTC, f-lab-maverick reviewed
회원가입시 중요한 비즈니스로직이 빠져있네요.
회원가입시 "아이디가 중복된 경우"를 체크하지 않습니다. 중복된 아이디를 어떻게 처리할 것인지, 이 때 어떤 예외를 발생시킬 것이며 이 예외가 발생되었을 때 사용자에게 어떤 메세지를 보내줄 것인지를 추가로 작성하여 push해주세요~

2024-04-20 00:15 UTC, f-lab-maverick requested changes
약간만 다듬으면 완성될것으로 보입니다. 파이팅입니다!

2024-04-20 00:15 UTC, f-lab-maverick commented on src/main/java/flab/gotable/controller/MemberAPIController.java
> +        }
딱 한번만 사용하는 변수는 선언하지 않는 것이 가독성에 좋습니다.
변수가 늘어날수록 개발자가 트래킹해야할 대상이 많아지고 메서드 읽는 것이 어려워질 수 있으니 아래와 같이 활용해주세요~

```suggestion
        if (memberService.isDuplicatedId(memberSignUpRequestDto.getId())) {
            throw new DuplicatedIdException(ErrorCode.DUPLICATED_ID, ErrorCode.DUPLICATED_ID.getMessage());
        }
```

2024-04-20 00:15 UTC, f-lab-maverick commented on src/main/java/flab/gotable/dto/MemberResponse.java
> +}
한번 만들고 변경되지 않을 상태를 만들 때에는 불변성을 보장해줄 수 있도록 `final`키워드를 사용하면 더더욱 좋습니다 👍 

```
    private final String status;
    private final T data;
    private final String message;
```

그리고 이렇게 final키워드로 만든 상태로 생성자를 만들면 `@AllArgsConstructor` 대신 `@RequiredArgsConstructor`를 사용하시면 되겠습니다.

2024-04-20 00:15 UTC, f-lab-maverick commented on src/main/java/flab/gotable/dto/request/MemberSignUpRequestDto.java
> +        member.setPassword(passwordEncoder.encode(memberSignUpRequestDto.getPassword()));
패스워드의 암호화는 비즈니스로직으로 Service레이어에서 암호화한 후, 암호화된 값으로 Member 도메인을 생성하도록 만들어주세요~ 그렇게 만들면 생성자에서 `PasswordEncoder `를 받을 필요가 없겠네요.

2024-04-20 00:15 UTC, f-lab-maverick commented on src/main/java/flab/gotable/exception/ErrorCode.java
> +    INTERNAL_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "내부 시스템 에러입니다.");
ErrorCode를 enum으로 관리해야할 이유가 있을까요? enum으로 관리하는 장점이 있을까요?
상수를 선언하고 싶은 것이라면 `httpStatus`, `message`를 상태로 가지는 클래스를 만들고, 상수를 선언하면 되지 않을까요?

2024-04-20 00:15 UTC, f-lab-maverick commented on src/main/java/flab/gotable/exception/ExceptionController.java
글로벌 익셉션 컨트롤러로 만드신거라면 반환타입으로 `MemberResponse`를 내려주지 않도록 해야 할 것으로 보입니다. 공통 에러 포맷을 만들어주세요~

2024-04-20 00:15 UTC, f-lab-maverick commented on src/main/java/flab/gotable/service/MemberService.java
> +    }
하나의 연산이지만, query가 발생하는 메소드는 명시적으로 `@Transactional`을 선언해주세요. 변경연산이 없는 경우에는 `readonly=true`옵션도 포함해주세요~ readonly 옵션에 따라 어떤점이 달라지는지도 한번 찾아보시겠어요?

2024-04-25 14:56 UTC, syoh98 commented on src/main/java/flab/gotable/service/MemberService.java
> +    }
`readonly=true` 옵션을 포함할 경우
* insert, update, delete가 수행됐을 때 rollback이 되어 코드를 안전하게 작성할 수 있습니다.
* 잠금없는 읽기가 가능하기 때문에 read만 하는 트랜잭션은 오버헤드가 발생하지 않습니다.
* DB가 master-slave 구조일 경우, 읽기 전용으로 master가 아닌 slave를 호출하기 때문에 DB 서버의 부하를 줄이고 최적화가 가능합니다.

2024-04-27 13:00 UTC, f-lab-maverick commented on src/main/java/flab/gotable/exception/ErrorCode.java
> +    INTERNAL_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "내부 시스템 에러입니다.");
저의 프로젝트에서는 enum으로 ErrorCode를 관리하는 것이 더 적절하다고 판단했습니다. => 실제 구현은 class로 되어있는데요, 위와같은 근거를 토대로 class로 관리한다고 말씀하신거겠죠?

2024-04-27 13:57 UTC, f-lab-maverick approved these changes
고생하셨습니다. 리뷰하나 확인해주시고, 수정한 후 머지해주세요~

2024-04-27 13:57 UTC, f-lab-maverick commented on src/main/java/flab/gotable/dto/ApiResponse.java
> +    }
status는 HTTP_STATUS_CODE로도 나타낼 수있는데 여기서도 필요한 값인가요? 한번 고민해주세요~

2024-04-29 12:04 UTC, merged